### PR TITLE
Added ability to create libraries without sources

### LINKED ISSUE #57: Failure to create library without sources
A library should be able to be created without sources at first, passing them later using CMake's `target_sources` function.

Currently, calling the `add_arduino_library` function without passing any sources simply fails CMake.

### PR DESCRIPTION
**Pull request by MrPointer**
Now one can create a library target using the `add_arduino_library` function without providing any sources to it at creation time.
It's important to note though that sources must be provided sometime using the `target_sources` function, otherwise execution will fail.

Fixes #57

### CODE REVIEW

**Comment by MrPointer** [comment]
@Nihlus Could you give this a try in your project?

**Comment by Nihlus** [comment]
That seems to work, but it's still failing when I attempt a call to  `find_arduino_library` afterwards.

**Comment by MrPointer** [comment]
@Nihlus Does this function somehow relate to testing this feature? Because you may be talking about #56 
If so - Could you please attach the CMake file you're using?

**Comment by Nihlus** [comment]
This feature works fine :)

**Pull request merged**
